from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from kpro.config import Config
from kpro.core import KproError, git, run, within, write_text

# Preserve quoted include names but blank comments/raw strings before finding directives.
TOKEN = re.compile(
    r'^[ \t]*#[ \t]*include[ \t]*<[^>\n]+>|//[^\n]*|/\*.*?\*/|R"([^ ()\\\t\r\n]{0,16})\(.*?\)\1"|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'',
    re.S | re.M,
)
INCLUDE = re.compile(r'^\s*#\s*include\s*[<"]([^>"\n]+)[>"]\s*$', re.M)


def clean_directives(text: str) -> str:
    def blank(match: re.Match) -> str:
        token = match[0]
        if token.startswith(("//", "/*", 'R"')):
            return "".join("\n" if ch == "\n" else " " for ch in token)
        return token

    return TOKEN.sub(blank, text)


def directives(text: str) -> dict[int, str]:
    cleaned = clean_directives(text)
    found = {}
    for match in INCLUDE.finditer(cleaned):
        # The pattern may absorb preceding blank lines: count the directive itself.
        offset = cleaned.index("#", match.start(), match.end())
        found[cleaned.count("\n", 0, offset)] = match[1]
    return found


def validate_include(name: str, prefix: str) -> str:
    path = PurePosixPath(name)
    if (
        not name.startswith(prefix)
        or ".." in path.parts
        or "\\" in name
        or path.is_absolute()
        or path.suffix != ".hpp"
        or path.as_posix() != name
    ):
        raise KproError(f"Invalid library include: {name}. Use <{prefix}category/name.hpp>.")
    return name


@dataclass
class Bundle:
    text: str
    files: list[str]
    dependencies: dict[str, list[str]]
    commit: str | None


def provenance(commit: str | None, tag: str | None, files: list[str]) -> str:
    lines = [
        "/*",
        " * Generated by kpro.",
        " *",
        " * Pre-existing library snapshot:",
        f" *   commit: {commit or 'working-tree (non-contest)'}",
    ]
    if tag:
        lines.append(f" *   tag: {tag}")
    lines += [
        " *",
        " * Expanded library files:",
        *[f" *   {name}" for name in files],
        " *",
        " * Contest solution source is not part of the pre-contest snapshot.",
        " */",
        "",
    ]
    return "\n".join(lines)


def expand(
    config: Config, source: Path, *, commit: str | None = None, tag: str | None = None
) -> Bundle:
    prefix = config.section("bundle")["library_prefix"]
    if commit:
        resolved = git(config.root, "rev-parse", "--verify", f"{commit}^{{commit}}")
        if resolved != commit:
            raise KproError("Snapshot must be a full immutable Git commit hash.")
    emitted: set[str] = set()
    active: list[str] = []
    files: list[str] = []
    dependencies: dict[str, list[str]] = {}

    def load(name: str) -> str:
        validate_include(name, prefix)
        relative = (config.path("library_include_root").relative_to(config.root) / name).as_posix()
        if commit:
            result = run(
                ["git", "show", f"{commit}:{relative}"],
                cwd=config.root,
                check=False,
                capture_output=True,
            )
            if result.returncode:
                raise KproError(
                    f"Library header {name} is absent from base_commit {commit}. Add contest-written code to the solution directly."
                )
            return result.stdout
        path = within(config.root, relative)
        if not path.is_file():
            raise KproError(f"Missing library header: {path}")
        return path.read_text(encoding="utf-8")

    def process(text: str, parent: str) -> str:
        parsed = directives(text)
        cleaned = clean_directives(text).splitlines()
        meaningful = [line.strip() for line in cleaned if line.strip()]
        outer_guard = (
            parent != "solution"
            and len(meaningful) >= 3
            and re.fullmatch(r"#\s*ifndef\s+(\w+)", meaningful[0])
            and re.fullmatch(
                r"#\s*define\s+" + re.fullmatch(r"#\s*ifndef\s+(\w+)", meaningful[0])[1],
                meaningful[1],
            )
            and re.fullmatch(r"#\s*endif", meaningful[-1])
        )
        conditional_depth = 0
        output = []
        dependencies[parent] = []
        for index, line in enumerate(text.splitlines(keepends=True)):
            clean_line = cleaned[index] if index < len(cleaned) else ""
            directive = re.match(r"\s*#\s*(\w+)\b", clean_line)
            if directive:
                if directive[1] in {"if", "ifdef", "ifndef"}:
                    conditional_depth += 1
                elif directive[1] == "endif":
                    conditional_depth -= 1
            name = parsed.get(index)
            if directive and directive[1] == "include" and name is None:
                raise KproError(
                    f"Unsupported include directive in {parent}: {line.strip()}. Use single-line literal includes."
                )
            if name and name.startswith(prefix):
                if conditional_depth > (1 if outer_guard else 0):
                    raise KproError(
                        f"Conditional library include in {parent}: {name}. Keep <{prefix}...> dependencies unconditional."
                    )
                validate_include(name, prefix)
                dependencies[parent].append(name)
                start = clean_line.index("#")
                end = clean_line.index(name, start) + len(name)
                before, after = line[:start], line[end + 1 :]
                if name in active:
                    raise KproError("Library dependency cycle: " + " -> ".join([*active, name]))
                if name in emitted:
                    output += [before, after]
                    continue
                active.append(name)
                files.append(name)
                body = process(load(name), name)
                active.pop()
                emitted.add(name)
                output += [
                    before,
                    f"// begin {name}\n",
                    body,
                    "\n" if body and not body.endswith("\n") else "",
                    f"// end {name}\n",
                    after,
                ]
            elif parent != "solution" and re.fullmatch(r"\s*#\s*pragma\s+once\s*", clean_line):
                # Preserve comments after pragma once, including multiline comments.
                match = re.search(r"#\s*pragma\s+once", line)
                output.append(line[: match.start()] + line[match.end() :] if match else "\n")
                continue
            else:
                output.append(line)
        return "".join(output)

    content = process(source.read_text(encoding="utf-8"), "solution")
    if config.section("bundle")["emit_provenance_comment"]:
        content = provenance(commit, tag, files) + content
    return Bundle(content, files, dependencies, commit)


def bundle_file(config: Config, source: Path, metadata: dict | None = None) -> Path:
    result = expand(
        config,
        source,
        commit=metadata["base_commit"] if metadata else None,
        tag=metadata.get("snapshot_tag") if metadata else None,
    )
    target = source.parent / "build" / "submit.cpp"
    write_text(target, result.text)
    return target
